import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "../chunk/header/Header";
import Footer from "../chunk/footer/Footer";

import './nullstyle.scss';
import './typography.scss';
import './global.scss';


const PTSans = localFont({
	src: [
		{
			path: "../fonts/PTSans-Bold.woff2",
			weight: "700",
			style: "normal",
		},
		{
			path: "../fonts/PTSans-Regular.woff2",
			weight: "400",
			style: "normal",
		},
	],
	variable: "--PTSans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en" className={PTSans.variable}>
			<body>
				<Header></Header>
				{children}
				<Footer></Footer>
			</body>
		</html>
	);
}
